# Generated by Django 2.2.3 on 2019-08-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofileinfo',
            options={'permissions': (('download_pdf', 'Puede descargar PDF'),)},
        ),
    ]
